# Generated by Django 2.1.3 on 2018-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='paleo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
